### ISSUE TITLE
copy the github permalink

### ISSUE THREAD

**Issue by Geczy** [abachman/vscode-copyfordocumentation#2]
when copying lines, could we also copy a markdown hyperlinked url to the github file with the commit specified? 

for example:

[.github/workflows/ci.yaml:8-13](https://github.com/abachman/vscode-copyfordocumentation/blob/f0c5ba0abed86972ce09bd14104e6adf04ae7d14/.github/workflows/ci.yaml#L8-L13):

```yaml
push:
  branches:
    - main
pull_request:
  branches:
    - main
```
